BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //Get all Cover Type Data
        public IActionResult Index()
        {
            IEnumerable<CoverType> coverTypes = _unitOfWork.CoverType.GetAll();
            return View(coverTypes);
        }

        //Create Page.
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CoverType coverType)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(coverType);
                _unitOfWork.Save();
                TempData["success"] = "Cover Type created succesfully";
                return RedirectToAction("Index");
            }

            return View(coverType);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            CoverType coverType = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);

            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        [HttpPost]
        public IActionResult Edit(CoverType coverType)
        {
            if (ModelState.IsValid)
            {
                if (coverType != null)
                {
                    if (coverType.Id == 0)
                    {
                        return NotFound();
                    }
                    _unitOfWork.CoverType.Update(coverType);
                    _unitOfWork.Save();
                    TempData["success"] = "Cover Type edited succesfully";
                    return RedirectToAction("Index");

                }
                else
                {
                    return NotFound();
                }
            }
            return View(coverType);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            CoverType coverType = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        [HttpPost]
        public IActionResult Delete(CoverType coverType)
        {
            if (coverType == null || coverType.Id == 0)
            {
                return NotFound();
            }
            _unitOfWork.CoverType.Remove(coverType);
            _unitOfWork.Save();
            TempData["success"] = "Cover type deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
<div class="border p-3 mt-4">
    <div class="row pb-2">
        <h2 class="text-primary">Create Covertype</h2>
        <hr/>
    </div>
    <div class="mb-3">
       <label asp-for="Name" class="control-label"></label>
        <input asp-for ="Name" class="form-control" />
        <span asp-validation-for ="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-action="Index" asp-controller="CoverType" class="btn btn-secondary">
            Back to List
        </a>
    </div>
</div>
</form>

@section Scripts{
    @{
        <partial name ="_ValidationScriptsPartial"/>
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method ="post">
<div class="border p-3 mt-4">
    <div class="row pb-2">
        <h2 class="text-primary">Delete Covertype</h2>
        <hr/>
    </div>

    <div class="mb-3">
        <label asp-for="Id"></label>
        <input asp-for="Id" class="form-control" readonly />
    </div>

    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" readonly/>
    </div>

    <div class="mb-3">
        <button type="submit" class="btn btn-danger w-150">Delete</button>
         <a asp-action="Index" asp-controller="CoverType" class="btn btn-secondary">
                Back to List
            </a>
     </div>
</div>
</form>

BulkyBookWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method = "post">
    <div class ="border p-3 mt-4">
        <div class="row pb-2">
              <h2 class="text-primary">Edit Covertype</h2>
            <hr/>
        </div>

        <div class="mb-3">
            <label asp-for="Id"></label>
            <input asp-for="Id" class="form-control" readonly/>          
        </div>

        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
            <a asp-action="Index" asp-controller="CoverType" class="btn btn-secondary">
                Back to List
            </a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}

<partial name ="_Notification"/>

<div class="container p-3">
    <div class = "row pt-4">
       <div class="col-6">
           <h2 class="text-primary">Cover Type List</h2>
       </div>  
       <div class = "col-6 text-end">
          <a asp-controller = "CoverType" asp-action ="Create" class =" btn btn-primary">
              <i class="bi bi-plus-circle"></i>&nbsp;
              Create Covertype
          </a>
       </div>
    </div>
    <br/><br/>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
             <th>
                 @Html.DisplayNameFor(model => model.Name)
             </th>
             <th></th>
             <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td style = "width:20%">@item.Id</td>
                <td style = "width:50%">@item.Name</td>
                 <td>
                    @* w-75 specifies a width of 75% -- https://getbootstrap.com/docs/4.0/utilities/sizing/
                       button group - wraps a series of buttons with .btn in .btn-group. https://getbootstrap.com/docs/4.0/components/button-group/
                      role="group" - Ensure correct role and provide a label
                        In order for assistive technologies (such as screen readers) to convey that a series of buttons is grouped, an appropriate role attribute needs to be provided. For button groups,
                        this would be role="group", while toolbars should have a role="toolbar".
                        https://getbootstrap.com/docs/4.0/components/button-group/
                      role="group" - Ensure correct role and provide a label
                    *@
                    <div class="w-75 btn-group" role="group">
                        <a class="btn btn-primary"
                        asp-controller="CoverType"
                        asp-action ="Edit"
                        asp-route-id="@item.Id"
                        >
                        <i class="bi bi-pencil-square"></i>
                        Edit
                        </a>
                    </div>
                    </td>

                    <td>
                    <div class="w-75 btn-group" role="group">
                        <a class="btn btn-danger" 
                           asp-controller="CoverType"
                           asp-action = "Delete"
                           asp-route-id ="@item.Id"
                           >
                            <i class="bi bi-trash"></i>Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>